### ISSUE TITLE
CoreText Example. 

### ISSUE THREAD

**Issue by kennycarruthers** [ryanlintott/Unicodices#1]
Ryan,

Here is an example of how to use CoreText to compute typographic bounds for doing text layout. If you're doing a lot of work with fonts that extend beyond their usual bounds, and thus get clipped by things like SwiftUI's `Text` control, then it's a lot easier (and better) to drop down to CoreText rather than trying to determine magic padding and line break values. 

I'm all but certain that SwiftUI, UIKit and AppKit all use CoreText under the hood for doing layout. Admittedly it's a lower level framework if you're coming from SwiftUI, but it pretty much offers all the text layout support you need. 

The attached example only does single line rendering, but doing multi-line rendering isn't much more work. In fact, Apple even has an example of how to do it online: 

[Core Text Programming Guide](https://developer.apple.com/library/archive/documentation/StringsTextFonts/Conceptual/CoreText_Programming/LayoutOperations/LayoutOperations.html#//apple_ref/doc/uid/TP40005533-CH12-SW11)

Hope this helps and good luck with the app.

**Comment by kennycarruthers** [comment]
```
//
//  CoreTextLineView.swift
//  Unicodices
//

import SwiftUI

// MARK: - CoreTextLineView

struct CoreTextLineView: View {
  
  /// Public Properties
  ///
  let font = UIFont(name: Junius.regular.rawValue, size: 35)!
  let textColor = UIColor.label
  let string: String
  
  /// body
  ///
  var body: some View {
    CoreTextRepresentableView(string: string, font: font, color: textColor)
      .border(.red)
  }
}

// MARK: - Previews

struct CoreTextLineView_Previews: PreviewProvider {
  static var previews: some View {
    VStack {
      Text("Normal Text Above")
      CoreTextLineView(string: "wrāþ-scræf")
      CoreTextLineView(string: "Ēalā, Woruld!")
      Text("Normal Text Below")
    }
  }
}

// MARK: - CoreTextRepresentableView

struct CoreTextRepresentableView: UIViewRepresentable {
  
  /// Public Properties
  ///
  let string: String
  let font: UIFont
  let color: UIColor
  
  /// makeUIView(context:)
  ///
  func makeUIView(context: Context) -> CoreTextLineUIView {
    return CoreTextLineUIView(string: string, font: font, color: color)
  }
  
  /// updateUIView(uiView:)
  ///
  func updateUIView(_ uiView: CoreTextLineUIView, context: Context) {
    // In a real-world application, it would probably be smart to reuse the
    // CoreTextLineUIView by moving `string` and `font` into public properties.
  }
}

// MARK: - CoreTextLineUIView

final class CoreTextLineUIView: UIView {

  /// Private Properties
  ///
  private let lineBounds: CGRect
  private let line: CTLine
  
  /// init(string:font:color:)
  ///
  init(string: String, font: UIFont, color: UIColor) {
    
    // You can apply whatever attributes make sense here. Note that the labels font and
    // font color need to get applied here because they become part of the CTLine.
    let attributes: [NSAttributedString.Key : Any] = [
      .font : font,
      .foregroundColor : color
    ]
    
    let attributedString = NSAttributedString(string: string, attributes: attributes)

    // This CoreText method accepts various options for computing a desired bounds.
    // Check the documentation and see how the options affect the returned value.
    self.line = CTLineCreateWithAttributedString(attributedString)
    self.lineBounds = CTLineGetBoundsWithOptions(self.line, [.useGlyphPathBounds])

    super.init(frame: .zero)
  
    // Disable opacity so that SwiftUI modifiers like backgroundColor work as expected.
    self.isOpaque = false
    
    // Increase hugging priority so that this view is only as large as it needs to be.
    // Adjust this accordingly if you desire different resizing behavior.
    self.setContentHuggingPriority(.required, for: .horizontal)
    self.setContentHuggingPriority(.required, for: .vertical)
  }
  
  /// init(coder:)
  ///
  required init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }
  
  /// intrinsicContentSize
  ///
  override var intrinsicContentSize: CGSize {
    return CGSize(width: lineBounds.width, height: lineBounds.height)
  }
  
  /// draw(rect:)
  ///
  override func draw(_ rect: CGRect) {
    guard let context = UIGraphicsGetCurrentContext() else {
      return
    }
    
    // Save the CGContext's current state.
    context.saveGState()
    
    // Invert the CGContext to a CoreText friendly origin in the lower-left corner.
    let transform = CGAffineTransform(a: 1, b: 0, c: 0, d: -1, tx: 0, ty: lineBounds.height)
    context.concatenate(transform)
    
    // Move the context's pen position based on the line's computed bounds and origin.
    context.textPosition.x -= lineBounds.origin.x
    context.textPosition.y -= lineBounds.origin.y
    
    // Draw the CoreText line.
    CTLineDraw(line, context)
    
    // Restore the CGContext.
    context.restoreGState()
  }
}

```

**Comment by kennycarruthers** [comment]
<img width="490" alt="Screen Shot 2021-10-28 at 9 48 18 PM" src="https://user-images.githubusercontent.com/15756/139377422-f4d97362-ddc6-4d05-8e6c-12ef73fe32d3.png">

**Comment by ryanlintott** [comment]
Thanks so much for the info! It looks like it's fixed the issue on the right but the bottom of one of the characters is still cropped. This might be a specific issue with the font though as I haven't seen vertical cropping issues in any other font. I'll have a look at the code and see if I can make an improved noClip using Core Text.

**Comment by kennycarruthers** [comment]
Are you sure it's actually clipping and it's not just the red border that is making it look clipped? If it is indeed clipping, then try passing in different options to `CTLineGetBoundsWithOptions`. Depending on what you pass in, you'll get a different value for the bounds returned. There's a bit of documentation in the header file. 

If things are still getting clipped, then perhaps the metrics in the font itself are wrong. If that's the case, then I doubt there's much you can do other than just applying random padding around things. You can test that theory by simply returning a larger `intrinsicContentSize` value and adjusting the `textPosition` accordingly. 

Unlike with SwiftUI's `Text` control, when you use the above code you're controlling whether there's clipping or not. CoreText will draw whatever the font says to draw while the values you provide for `intrinsicContentSize` will control the "clipping". 

It's hard to track down the WWDC 2012 videos, but someone has at least posted a PDF of the slides from Session 226, which covers the issue you're dealing with: 

[WWDC 2012 - Core Text and Fonts](https://docs.huihoo.com/apple/wwdc/2012/session_226__core_text_and_fonts.pdf)

Good luck!

**Comment by ryanlintott** [comment]
It's just barely clipping. I used .background(Color.clear.border(.pink)) and you could still see it going to the edge.
<img width="137" alt="image" src="https://user-images.githubusercontent.com/2143656/141820228-bbbcb02b-ab68-4176-bb8d-b44605c17a9b.png">
It looks like it might only be clipping the pixels after antialiasing where some fractional pixels are right at the edge. It's pretty minor.
I've tried the other `CTLineGetBoundsWithOptions` but none extended the borders.
I don't think the font metrics are wrong (at least not in a way that effects this boundary) as it's also happening with Zapfino and others.
One additional issue with this approach is you lose a lot of the SwiftUI Text features like accessibility and the baseline alignment guides. Like the others it still won't work with multiple lines and requires the MultiLineTextView or similar to stack them.

I've included your CoreText versions in the package and added a 1 pixel padding to `lineBounds` and this seems to fix any clipping.
```
let glyphPathBounds = CTLineGetBoundsWithOptions(self.line, [.useGlyphPathBounds])
self.lineBounds = CGRect(
  x: glyphPathBounds.minX - padding,
  y: glyphPathBounds.minY - padding,
  width: glyphPathBounds.width + (padding * 2),
  height: glyphPathBounds.height + (padding * 2)
)
```

**Comment by kennycarruthers** [comment]
Sounds good... I'll leave you with the final comments: 

If you're seeing sub-pixel clipping, then that's likely because the `textPosition` needs to be set to a whole number. Just call `ceil` or `floor` as appropriate. I suspect the values for `lineBounds.origin` are fractional and causing the bleed. Just round them to whole numbers in the appropriate direction. 

For multiline labels and paragraphs, CoreText can handle all of the line breaking for you. (It's what CoreText is inherently designed to do.) Apple has an example on their website and it's the basis for pretty much all text rendering on iOS and macOS. 

You know more about SwiftUI than I do, but I'm pretty sure for accessibility you can just add the appropriate accessibility traits to a custom view using the appropriate view modifiers. A label is a pretty straight forward, non-interactive control so it's unlikely you need to do anything special other than telling SwiftUI that it's actually a label. 

Not sure about the baseline guides, but since SwiftUI does support custom views, I imagine there's a way to specify the layout guides, but I don't have any experience. 

Anyways, good luck with the project. Ciao.

**Comment by ryanlintott** [comment]
Thanks so much again for all the Core Text info and code. I still have a lot to learn about it for sure.
I'll look into better rounding to improve the sub-pixel clipping.
And yes, I can use SwiftUI to add the accessibility elements and possibly the baseline guides back in again.
I really hope all this code becomes obsolete with a future SwiftUI update but either way it's been fun figuring all of this out.
